### ISSUE TITLE
Debugging individual test cases does not work

### ISSUE THREAD

**Issue by Simn** [vshaxe/haxe-test-adapter#13]
settings.json:

```
	"haxeTestExplorer.testCommand": [
		"${haxe}",
		"build.hxml",
		"--interp",
		"-lib",
		"test-adapter"
	],
	"haxeTestExplorer.launchConfiguration": "Interpreter"
```

launch.json:
```
		{
			"name": "Interpreter",
			"type": "haxe-eval",
			"request": "launch",
			"args": ["build.hxml", "--interp"]
		}
```

build.hxml:
```
-debug
-D dump=pretty

-cp source
-main Main
-lib utest
```

Main.hx:

```haxe
import utest.ITest;
import utest.Assert;

class TestClass implements ITest {
	public function new() {}

	public function test1() {
		Assert.isTrue(true);
	}

	public function test2() {
		Assert.isTrue(true);
	}
}

class Main {
	static public function main() {
		utest.UTest.run([new TestClass()]);
	}
}
```

Problem: 
![2019-03-04_16-53-42](https://user-images.githubusercontent.com/634365/53744864-2c453a00-3e9e-11e9-8add-00b20afa6777.gif)

**Comment by Gama11** [comment]
See https://github.com/vshaxe/haxe-test-adapter#debugging

**Comment by Simn** [comment]
Adding `-lib test-adapter` to my build.hxml changes nothing though.

**Comment by Gama11** [comment]
Hm, having a hard time testing this with `samples/utest` because eval-debugger seems to crash there.. :D It's similar to that earlier issue, where it dies shortly after hitting a breakpoint and there's no ouptut..

**Comment by Simn** [comment]
Make sure you're on latest eval-debugger, not the vshaxe submodule reference.

**Comment by Gama11** [comment]
Oh, right.. I thought I was, but I must've used "discard all changes" in SourceTree at some point.

**Comment by Simn** [comment]
Thanks! This helps me a lot.

Do I have to rebuild something or is pulling enough?

**Comment by Gama11** [comment]
The extension has to be rebuilt, but I'm also making a 1.2.2 release with this fix.
