### ISSUE TITLE
Can we make the inline error comments copyable?

### ISSUE THREAD

**Issue by Simn** [vshaxe/haxe-test-adapter#14]
I'm talking about this:

![Code_2019-03-11_09-29-25](https://user-images.githubusercontent.com/634365/54109878-2ab8cc00-43e0-11e9-98c8-6d9b58610bf9.png)

I often write tests by letting them fail and then copying the "actual" output from the error. This is very convenient when I'm not quite sure what exactly the expected value is, which is often the case when strings are involved.

**Comment by AlexHaxe** [comment]
When you click a failed test in test explorer or use "Show log" in codelens, it will print it's error message to output window. It should automatically show up - at least it does for me. 
You can copy text from there, if that helps.

**Comment by Gama11** [comment]
What Alex said.

Note that we don't control _any_ of the UI. This includes the Test Explorer tree view, code lens, inline decorations, the log output channel... That's all done by Test Explorer UI, we merely supply the data.

Looking through the decorations API a bit, I'm not sure it's even possible on a VSCode level to make the text of decorations selectable. Perhaps via [`textDecoration`](http://vshaxe.github.io/vscode-extern/vscode/ThemableDecorationAttachmentRenderOptions.html#textDecoration), if that allows arbitrary CSS to be injected.
