### ISSUE TITLE
No results of buddy tests in the extension panel

### ISSUE THREAD

**Issue by djaonourside** [vshaxe/haxe-test-adapter#16]
My env: haxe#4.0.0-rc.3, buddy#2.10.2, test-adapter#1.2.1, Haxe Test Explorer#1.2.3
I see no any results of my tests in the extension panel. 
generated .unittest/position.js:
```
{
	"test.data.EnumMapTests": {
		"pos": {
			"line": 6,
			"file": "test/src/test/data/EnumMapTests.hx"
		},
		"methods": {}
	}
}
```

**Comment by AlexHaxe** [comment]
Do you have a `.unittest/results.json` after running with `-lib test-adapter`? 

Can you `git clone https://github.com/vshaxe/haxe-test-adapter` and open VSCode in `haxe-test-adapter/samples/buddy` and try to run tests there? 
If that works you are doing something different in your test project and we can try to figure out what. 
If it doesn't then there is something wrong with your setup, that we need to work out and see what's broken or why it doesn't run properly.

**Comment by djaonourside** [comment]
The buddy sample works as expected. The problem was solved by removing -lib hxnodejs, -js bin/test.js and adding -x Main flag to test.hxml

**Comment by AlexHaxe** [comment]
Ahh, I see. Haxe-test-explorer launches just one .hxml file (defaults to `test.hxml`) and expects it to compile and run tests. If you only compile and not run tests, then having no results is to be expected.

You can run tests using NodeJS target, but you need to put `-cmd node bin/test.js` at the end of your test.hxml file.

**Comment by djaonourside** [comment]
Now it's clear. Thanks for replies:)
