### ISSUE TITLE
Last assert overrides error.

### ISSUE THREAD

**Issue by karliss** [vshaxe/haxe-test-adapter#17]
- Testing framework:  utest [1.10.1]
- haxe target: --interp
- haxe version: 4.0.1

When a test case contains multiple asserts haxe-test-adapter reports that test succeeded  if last of the asserts succeed. Running the tests from command line correctly reports that testcase failed if any of asserts fail.

![image](https://user-images.githubusercontent.com/7101031/68551953-8e394480-041a-11ea-9672-a874a885096a.png)

**Comment by AlexHaxe** [comment]
Version 1.2.6 was released earlier today, it includes my bugfix.

**Comment by karliss** [comment]
Works. Thank you for quick fix.
