### ISSUE TITLE
Example for node.js env

### ISSUE THREAD

**Issue by hansagames** [vshaxe/haxe-test-adapter#18]
Hi,
in readme its stated that sys and node.js is supported, is there any example configuration how to setup it for node as I saw only Neko targets :) mostly interested for buddy.

Thank you

**Comment by AlexHaxe** [comment]
in `samples/buddy` folder simply modify `test.hxml` to look like this:
```hxml
-cp src
-lib buddy
-lib hxnodejs
-main Main
-js main.js

-cmd nodejs main.js
```

**Comment by hansagames** [comment]
Thank you got working with this setup
```hxml
-lib buddy
-lib hxnodejs
-cp src
-cp tests
-main Main
-js main.js
-D buddy-colors
-cmd node main.js
```
