### ISSUE TITLE
Nested describe calls for buddy

### ISSUE THREAD

**Issue by hansagames** [vshaxe/haxe-test-adapter#19]
Hi, 
made an issue based on discussion [here](https://community.haxe.org/t/test-explorer-in-vscode/2436)

Would it be possible to show nested describe calls in tree view, as right now it shows only last describe before `it`.

Example:
```haxe
class ATest extends BuddySuite {
	public function new() {
		describe("ATest", {
                describe("testing function", {
                        it("should do some stuff", {...});
                });
         });
```

**Comment by AlexHaxe** [comment]
fixed by #22
